특정 학생 조회 API (admin)
BCSDLab/KOIN_API pull request #197
Opened 2023-04-03 08:10 UTC by daheeParkk

특정 학생 조회 api : admin 페이지에서 id로 학생을 조회하면 StudentResponse DTO에 담아 반환하는 api입니다

< **코드를 추가한 위치** >
controller/admin/AdminUserController 
service/admin/AdminUserService
service/admin/AdminUserServiceImpl

< **새로 만든 클래스** >
dto/admin/user/response/UserResponse
dto/admin/user/student/StudentResponse
mapstruct/admin/user/StudentConverter

2023-04-03 08:27 UTC, Kim-Juwon requested changes
이번 API 개발 경험을 통해 다음을 경험해보셨을 겁니다!
- dto 사용
- API 문서화
- 200번대 응답 외에, 다른 응답(ex. 400번대)들을 Exception handling을 통해 처리

위에 언급된 내용들이 왜 필요하고, 자신이 어떻게 처리했었는지도 한번 고민해보는 시간을 가지면 좋을 것 같네요!😀

첫 API 개발 수고하셨고,
리뷰해드린부분 수정 부탁드립니다.

2023-04-03 08:27 UTC, Kim-Juwon commented on src/main/java/koreatech/in/mapstruct/admin/user/StudentConverter.java
> +    StudentResponse toStudentResponse(Student student);
중간에 개행을 넣어주세요.

그리고 toStudentResponse에 대해 MapstructProcessor가 만든 구현 클래스 내용을 직접 확인해보시고 테스트 해보셨나요?

2023-04-03 08:27 UTC, Kim-Juwon commented on src/main/java/koreatech/in/service/admin/AdminUserService.java
> +    StudentResponse getStudentForAdmin(Integer userId) throws Exception;
메소드 이름에서 `ForAdmin`을 제거해주세요.

이 부분에 대해서는 오늘 동아리방에서 모였을때 설명드리도록 하겠습니다.

2023-04-03 08:27 UTC, Kim-Juwon commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        Optional.ofNullable(user).orElseThrow(() -> new BaseException(INQUIRED_USER_NOT_FOUND));
한번에 처리하기 위해 이렇게 코드를 작성할 수도 있을 것 같아요!
참고만 해도 괜찮을 것 같아요.

```suggestion
        User user = Optional.ofNullable(adminUserMapper.getUserById(userId))
                            .orElseThrow(() -> new BaseException(INQUIRED_USER_NOT_FOUND));
```

2023-04-03 08:37 UTC, daheeParkk commented on src/main/java/koreatech/in/mapstruct/admin/user/StudentConverter.java
> +    StudentResponse toStudentResponse(Student student);
확인해 보겠습니다..!

2023-04-03 08:37 UTC, daheeParkk commented on src/main/java/koreatech/in/service/admin/AdminUserService.java
> +    StudentResponse getStudentForAdmin(Integer userId) throws Exception;
넵

2023-04-03 08:38 UTC, daheeParkk commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        Optional.ofNullable(user).orElseThrow(() -> new BaseException(INQUIRED_USER_NOT_FOUND));
수정하겠습니다!

2023-04-04 06:51 UTC, Invidam requested changes
mapstruct, Exception 처리, DTO 변환 등이 잘 되어있네요 👍

코드 리뷰 남겼으니 참고하여 수정 바랍니다!!

2023-04-04 06:51 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/user/response/UserResponse.java
> +    private Date updated_at;
Response 객체에 required, optional 설정하고 예시, 설명(제약 조건 등)을 명시해야 합니다.

[참고 자료](https://docs.google.com/document/d/1JB9oOTqvGTsX_nGkosYRjZObR-LGmW-Ux3SEfFhVV1M/edit)

2023-04-04 06:51 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
>  import static koreatech.in.exception.ExceptionInformation.*;
```suggestion
import static koreatech.in.exception.ExceptionInformation.INQUIRED_USER_NOT_FOUND;
import static koreatech.in.exception.ExceptionInformation.PAGE_NOT_FOUND;
import static koreatech.in.exception.ExceptionInformation.PASSWORD_DIFFERENT;
import static koreatech.in.exception.ExceptionInformation.USER_NOT_FOUND;
```
처럼 와일드카드 대신 일반 improt문들을 사용하면 좋을 것 같습니다.

설정 방법: https://dev-kani.tistory.com/39
참고 문서: https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2023-04-04 06:51 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +import java.util.*;
```suggestion

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
```

2023-04-04 06:51 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        return StudentConverter.INSTANCE.toStudentResponse((Student) user);
`(Student) user`에서 학생이 아닌 User가 들어오면 500번 예외가 발생하네요.
학생이 아니라는 예외처리가 필요할 것 같습니다.

2023-04-04 06:53 UTC, daheeParkk commented on src/main/java/koreatech/in/dto/admin/user/response/UserResponse.java
> +    private Date updated_at;
넵 명시하겠습니다!

2023-04-04 06:53 UTC, daheeParkk commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
>  import static koreatech.in.exception.ExceptionInformation.*;
넵

2023-04-04 06:53 UTC, daheeParkk commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        return StudentConverter.INSTANCE.toStudentResponse((Student) user);
넵 추가하겠습니다

2023-04-04 07:06 UTC, Kim-Juwon commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        return StudentConverter.INSTANCE.toStudentResponse((Student) user);
저번에 설명드린 down casting이 불가능한 경우를 다시 생각해보세요!

2023-04-04 07:07 UTC, daheeParkk commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        return StudentConverter.INSTANCE.toStudentResponse((Student) user);
넵!

2023-04-05 11:07 UTC, merged

2023-04-17 17:09 UTC, songsunkook commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    ResponseEntity<StudentResponse> getStudent(@ApiParam(name = "id", required = true) @PathVariable("id") int id) throws Exception {
@daheeParkk 
```suggestion
    ResponseEntity<StudentResponse> getStudent(@ApiParam(required = true) @PathVariable("id") int id) throws Exception {
```
ApiParam에서는 PathVariable는 name을 사용하면 파라미터 이름과 다를 시 스웨거에서 URL에 변수를 매핑시키지 못합니다.... 따라서 PathVariable 파라미터에 ApiParam을 사용한 설명을 할 때는 value를 통해 진행하고, ApiParam의 name을 사용하는 경우는 RequestBody를 설명할 때로 제한하는 것이 바람직해 보입니다.