Feature/admin update owner api
BCSDLab/KOIN_API pull request #206
Opened 2023-04-13 02:25 UTC by johnny19991006

제가 아직 해결을 다 못했는데 기한이 너무 늦은거 같아 1차적으로 제출하겠습니다!
커밋 컨벤션도 마지막 올릴때는 양식에 맞게 수정하겠습니다!

2023-04-13 12:47 UTC, Invidam requested changes
코드 리뷰 남깁니다!

UPDATE API 부분은 GET API 보다 난이도가 있는 작업이라 고려할 부분이 많았을 것 같아요 😥
하지만 그 만큼 배울 부분도 많으니 **지금처럼 열심히 해주시길 바랍니다!** 🤗

q(≧▽≦q)

2023-04-13 12:47 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +            @ApiParam(value = "user_id", required = true) @PathVariable("id") Integer userId,
![image](https://user-images.githubusercontent.com/71889359/231753901-7bcba661-19bc-485b-ae53-d9a9f9951f86.png)
![image](https://user-images.githubusercontent.com/71889359/231753952-226895cf-fda1-4db0-b17f-a4da14c306c2.png)

@daheeParkk @songsunkook 
통일이 필요할 것 같아요~

| Parameter | Description |
| --- | ---|
| id | id |
| id | user_id |
| user_id | user_id |


중에서..

2023-04-13 12:47 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +        adminUserService.updateOwner(userId, request);
request에 대해 xss Check가 필요할 것 같아요!
```
        try {
            request = StringXssChecker.xssCheck(request, request.getClass().newInstance());
        } catch (Exception exception) {
            throw new BaseException(ExceptionInformation.REQUEST_DATA_INVALID);
        }
```
: ownerController 예시

- 참고: https://4rgos.tistory.com/1
- 참고: https://naver.github.io/lucy-xss-filter/kr/

2023-04-13 12:47 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +    private String company_registration_certificate_image_url;
`company_registration_certificate_image_url`은 `List<OwnerAttachment> attachments;` 로 대체되어 사용하지 않아, 없어도 될 것 같아요~

2023-04-13 12:47 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +
참고한 코드가 있을까요?

2023-04-13 12:47 UTC, Invidam commented on src/main/resources/mapper/admin/AdminOwnerMapper.xml
> +            company_registration_certificate_image_url=#{owner.company_registration_certificate_image_url},
`company_registration_certificate_image_url` 대신 `owner_attachments` 목록을 수정해야 할 것 같아요 😥

2023-04-13 12:47 UTC, Invidam commented on src/main/resources/mapper/admin/AdminOwnerMapper.xml
> +            grant_event=#{owner.grant_event}
grant_shop 까지 갱신👍

꼼꼼히 확인한 티가 나네요!

2023-04-13 12:47 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/user/owner/request/OwnerUpdateRequest.java
> +package koreatech.in.dto.admin.user.owner.request;
admin 패키지의 별도 dto로 잘 만들었네요! 👍👍

2023-04-14 07:07 UTC, songsunkook commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +            @ApiParam(value = "user_id", required = true) @PathVariable("id") Integer userId,
저는 
| Parameter | Description |
| --- | --- |
| id | user_id |

가 좋을 것 같습니다!

2023-04-15 07:49 UTC, johnny19991006 commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +            @ApiParam(value = "user_id", required = true) @PathVariable("id") Integer userId,
그럼 parameter->id, description->user_id 좋을것 같아요!!

2023-04-15 07:49 UTC, johnny19991006 commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +        adminUserService.updateOwner(userId, request);
넵 추가하겠습니다!!

2023-04-15 07:50 UTC, johnny19991006 commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +    private String company_registration_certificate_image_url;
저번에 말해주셨던 테이블 관계 한번더 파악후 고쳐보겠습니다~~!

2023-04-15 07:50 UTC, johnny19991006 commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +
AdminMember에서 참고하였습니다!

2023-04-15 07:50 UTC, johnny19991006 commented on src/main/resources/mapper/admin/AdminOwnerMapper.xml
> +            company_registration_certificate_image_url=#{owner.company_registration_certificate_image_url},
넵!!!!!

2023-04-17 03:15 UTC, daheeParkk commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +            @ApiParam(value = "user_id", required = true) @PathVariable("id") Integer userId,
저도 id, user_id로 수정하겠습니다!

2023-04-17 03:17 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +            @ApiParam(value = "user_id", required = true) @PathVariable("id") Integer userId,
추후 한명이 도맡아 하는 게 나을듯

2023-04-17 14:41 UTC, Invidam commented
PR 이름 다른 PR이름들 처럼 변경해주고
[참고자료](https://docs.google.com/document/d/1V4BReXfmOCrBn9HxD8JT6Xgj7IMDg4S8IvzNK7ZeoEo/edit) 참고하여 커밋 메시지 컨벤션도 꼭 지켜줘! 

변경내용 적용 전까지 draft 한 뒤 변경 완료되면 취소하면 될 듯
![image](https://user-images.githubusercontent.com/71889359/232496359-0b6891cc-d005-428d-991f-25e7601fff4a.png)

2023-05-13 16:38 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +
1. Owner이라는 도메인(다양할 곳에서 활용 될) update 관련 역할이 꼭 들어가 있어야 하는 지 모르겠어요. ( `OwnerForUpdate` 같은 객체를 만들면 좋았을 것 같아요)
2. Object.equals 대신 래퍼 클래스의 equals 를 활용하면 더 좋을 것 같아요.
3. 다른 기능들을 참고하는 건 좋지만, 완벽한 코드들이 아니니 개선점을 고민해보면 좋겠어요

2023-05-13 16:40 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        Owner existingOwner=(Owner)user;
`(Owner)user` 에서
userId를 통해 받아온 사용자가 Owner이 아니라면 에러가 발생합니다.
user 안에 Owner이 있는지 검사하는 메서드를 추가해주세요.

2023-05-13 19:36 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        Owner existingOwner=(Owner)user;
넵 추가 완료하였습니다!

2023-05-13 19:36 UTC, johnny19991006 commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +
이 부분 좀더 유의하여 다음번에 조금더 깔끔하게 진행하겠습니다.

2023-05-14 01:22 UTC, Invidam commented
1. `ClassCastException `발생 (사장님이 아닌 유저에 대해 업데이트를 실행한 경우)
2. Swagger에 request model 표시가 `normal`의 것으로 나옴 (아마 swagger 상에서 이름중복 오류일텐데, `@ApiModel으로 이름을 다르게 설정하는 것` 등을 고려해보세요)
3. ```
    @Size(max = 12, message = "사업자등록번호의 길이는 최대 12자 입니다")
    @ApiModelProperty(notes = "사업자등록번호 \n" + "- not null \n" + "- 최대 12자", example = "2019161116", required = true)
    ```
    등등 틀린 내용을 포함하여 가독성이 떨어진다거나, 맞지 않은 표현이거나 하는 내용이 많습니다.
API 문서를 확인하는 클라이언트 측에 대한 고려도 필수입니다.

=> PR 요청은 코드 확인 요청이 아니라 머지 요청입니다. 머지가 된 내용은 스테이지-프로덕션에 올라가고 클라이언트-사용자가 사용합니다. PR을 날리기 전 여러 사항들을 꼼꼼히 확인한 후 요청해주세요!

2023-05-14 03:08 UTC, johnny19991006 commented
> 1. `ClassCastException `발생 (사장님이 아닌 유저에 대해 업데이트를 실행한 경우)
> 2. Swagger에 request model 표시가 `normal`의 것으로 나옴 (아마 swagger 상에서 이름중복 오류일텐데, `@ApiModel으로 이름을 다르게 설정하는 것` 등을 고려해보세요)
> 3. ```
>     @Size(max = 12, message = "사업자등록번호의 길이는 최대 12자 입니다")
>     @ApiModelProperty(notes = "사업자등록번호 \n" + "- not null \n" + "- 최대 12자", example = "2019161116", required = true)
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    등등 틀린 내용을 포함하여 가독성이 떨어진다거나, 맞지 않은 표현이거나 하는 내용이 많습니다.
>    API 문서를 확인하는 클라이언트 측에 대한 고려도 필수입니다.
> 
> => PR 요청은 코드 확인 요청이 아니라 머지 요청입니다. 머지가 된 내용은 스테이지-프로덕션에 올라가고 클라이언트-사용자가 사용합니다. PR을 날리기 전 여러 사항들을 꼼꼼히 확인한 후 요청해주세요!

2023-05-16 02:32 UTC, Invidam requested changes
검증 로직 중요하니 잘 확인해주세요~

작업하기 전 비슷한 기능을 가진 코드가 있는 지 한 번 검토해본 뒤 작업을 해도 좋을 것 같아요!

+ 충돌 문제도 있어요

2023-05-16 02:32 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/user/owner/request/OwnerUpdateRequest.java
> +    @ApiModelProperty(notes = "사업자등록번호 \n" + "- not null \n" + "- 최대 12자", example = "999-99-99999", required = true)
@NotBlank(message = "사업자 등록 번호는 필수입니다.")
    @Pattern(regexp = "^[0-9]{3}-[0-9]{2}-[0-9]{5}", message = "사업자 등록 번호 형식이 올바르지 않습니다.")
    @ApiModelProperty(notes = "사업자 등록 번호 \n"
            + "- not blank \n"
            + "- 사업자 등록 번호 형식이어야 함"
            , example = "012-34-56789"
            , required = true
    )
    
    
In `OwnerRegisterRequest`

2023-05-16 02:32 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/user/owner/request/OwnerUpdateRequest.java
> +    @ApiModelProperty(notes = "이메일 \n" + " -not null \n" + "-최대 100자", example = "testmailnotvalid@gmail.com", required = true)
수정 API에서 이메일만 필수로 입력하게 한 이유가 있을까요?
- 전부 다 NotNull 이거나
- 전부 다 CanNull 이어야
할 것 같아서요
PUT vs PATCH 생각하면 전부 필수여야 할 것 같기도 하고..

(example에 테스트 이메일을 넣은 건 좋네요 👍)

2023-05-16 02:32 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/user/owner/request/OwnerUpdateRequest.java
> +    @ApiModelProperty(notes = "상점 수정 권한", example = "default=0")
` example = "false"` 대신 ` example = "default=0"`을 사용한 이유가 있을까요? swagger 상에선 잘 보여지긴 하는데..

2023-05-16 10:20 UTC, johnny19991006 commented on src/main/java/koreatech/in/dto/admin/user/owner/request/OwnerUpdateRequest.java
> +    @ApiModelProperty(notes = "상점 수정 권한", example = "default=0")
아 저부분은 삭제하겠습니다!

2023-05-16 10:24 UTC, johnny19991006 commented on src/main/java/koreatech/in/dto/admin/user/owner/request/OwnerUpdateRequest.java
> +    @ApiModelProperty(notes = "이메일 \n" + " -not null \n" + "-최대 100자", example = "testmailnotvalid@gmail.com", required = true)
전에 create문에서는 email이 꼭 필요하였지만 지금은 필요하지 않아서 NOTNull을 뺐는데, 아래에서 @APIModelProperty에서는 제외를 못했습니다

2023-05-17 09:57 UTC, Invidam commented
`User.update`, `UserUpdateRequest`, `UserUpdateResponse`를 이용하도록 변경 필요 (normal-student-update 꼭 참고!)합니다.

2023-05-17 10:00 UTC, Invidam commented
의도한 대로 동작하는 것 같으나, 중복 체크 과정에 있어 궁금함이 있어 댓글 남깁니다.

```
{
  "gender": 0,
  "identity": 0,
  "is_graduated": false,
  "major": "컴퓨터공학부",
  "name": "박한수123",
  "nickname": "phs123",
  "password": "a0240120305812krlakdsflsa;1235",
  "phone_number": "010-0000-0000",
  "student_number": "2013136000"
}
```

라는 정보를 가진 회원을 업데이트 API 아래와 같이 변경하면 닉네임 오류가 뜹니다. 이래도 괜찮을까요?
```
{
  "gender": 1,
  "identity": 0,
  "is_graduated": false,
  "major": "컴퓨터공학부",
  "name": "박한수123",
  "nickname": "phs123",
  "password": "a0240120305812krlakdsflsa;1235",
  "phone_number": "010-0000-0000",
  "student_number": "2013136000"
}
```

제가 알기론 프론트에선 위 JSON과 같이 변경된 필드(gender)를 포함한 모든 정보(JSON 내용 전문)를 요청한다고 알고있는데 그렇다면 매번 닉네임 중복 에러가 터질 것 같아요.

**즉, 이미 저장된 본인의 정보(닉네임, 이메일 등)를 요청했음에도 다른사람이 이미 사용중인 정보(중복된 정보)를 입력했다는 예외처리가 발생할 것 같습니다.**

결론은
1. 자신의 정보를 입력했음에도 다른사람의 정보를 입력하였다는 예외가 뜨는지 확인.
2. 클라이언트 요청사항이 어떻게 이루어지고, 해당 예외가 떠도 되는지 안되는지 확인.
3. 안되는 경우 아래 API들까지 점검

- normal student update
- normal owner update
- admin student update
- admin owner update

필요합니다.

2023-05-17 10:02 UTC, Invidam commented
1. **머지하기 전 필요한 리팩터링**이 반영되면 머지하겠습니다.


2. **동작 오류인지 판단이 필요한 내용** 이 오류가 맞다면 이슈를 파서 작업해주세요.
(문제 상황, 해결을 위해 어떠한 절차가 필요한지, 어떻게 해결했는지 서술)

2023-05-17 16:09 UTC, johnny19991006 commented
### 일단 리팩토링 해야 할 부분들은 모두 완료가 되었습니다. 
다만 지적해주신 email,사업자번호,닉네임의 경우 전체를 받아오는 경우에서는 말씀하신 문제가 발생할것 같습니다. 
일단 adminstudent에서도 이러한 문제가 있는것 같고, student에서는 중복된 경우를 잡아주는데, 
이렇게 될 경우 매퍼파일, 서비스impl파일을 통채로 갈아엎어 작업을 진행하던 중, 시간이 많이 소요되어 일단 올린후, 시간이 나면 다시 리팩토링을 해보겠습니다.

2023-05-20 13:14 UTC, Invidam commented
잠깐 확인하였는데 개선사항 있을 것 같아 코멘트 남깁니다.

1. 기능완성 이후 벌어지는 중복 방지에 대해서는 별도 브랜치를 파 PR을 날리는 게 좋았을 것 같습니다.
> 동작 오류인지 판단이 필요한 내용이 오류가 맞다면 이슈를 파서 작업해주세요. 라고 남겼었어요 😂

원하는 방향
:
![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/d614766c-cace-49ff-a0c9-569974ddf49e)

이대로 가면 완성될 결과물
:
![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/972e339f-f3b6-4777-a990-ee034a5239ea)

2023-05-20 13:21 UTC, Invidam commented
2. {성별, 이메일, 닉네임, 사업자 등록번호} 모두 중복 확인하기 위해 칼럼들을 매번 조회합니다. 업데이트할 때마다 매번 중복가능한 필드들을 중복체크하면 너무 비효율적일 것 같아요. DB에서 가져온 자기자신의 데이터와 중복체크를 하려고하는 데이터가 같은 경우는 중복체크를 안할 수 있을 것 같아요.

2023-05-20 13:59 UTC, johnny19991006 commented
앗넵! 직전에 했던 부분에서 머지가 안되어서 admin owner update부분만 수정하고 그 이후에 나머지 부분들을 이슈를 파서 하는 줄 알았습니다! 
1.일단 admin owner만 아래 피드백 주신 부분만 고쳐서 리뷰요청드릴까요?
2. 다시 전으로 돌리고 머지되면 이슈를 파서 중복오류만 다시 잡을까요?

추가로 두번째 피드백 주신 부분은 한번더 고민하고 해결하겠습니다!

2023-05-25 14:39 UTC, johnny19991006 commented
owner api1,2모두 완료되었습니다

2023-05-27 05:21 UTC, merged

2023-05-27 05:51 UTC, Invidam commented
첫 PR 수고했어요!!