Feature : 사장님 권한 요청 허용 API
BCSDLab/KOIN_API pull request #221
Opened 2023-05-01 15:28 UTC by daheeParkk

**사장님 권한 요청 허용 API : 사장님의 id를 받고 권한을 허용해 주는 API입니다.**

존재하지 않는 user일 경우,  owner의 id가 아닐 경우, 이미 인증된 회원일 경우에 대해 예외 처리하였습니다.  
mapper에 ownerId로 is_authed만 업데이트하는 쿼리문을 작성하였습니다.

---

< 새로 만든 오류 >
- 조회한 id가 사장님이 아닐 때 (code: 101018)  -> 409 CONFLICT
- 인증된 회원일 때 (code: 101019)  -> 409 CONFLICT

2023-05-01 15:43 UTC, ChoiWonBeen commented
@daheeParkk @Invidam 이 과정에서 상점 ID도 연결해주는게 이상적일 것 같은데, 이건 따로 API를 쓰게될까요?
상점 상세 PUT api를 쓴다던가...

2023-05-01 16:14 UTC, daheeParkk commented
@ChoiWonBeen 
"`사장님 권한을 허용`해주면서 `상점 id를 연결`하는 것"을 동시에 하는 것과 분리하는 것이 비슷하다고 생각됩니다.
프론트 단에서 더 편하신 방향으로 진행하겠습니다! 😋

2023-05-01 16:15 UTC, ChoiWonBeen commented
허용할때 상점id하나 입력해서 허용해주는게 맞는거같아여

2023-05-01 16:17 UTC, daheeParkk commented
@ChoiWonBeen 
넵!

2023-05-04 05:34 UTC, Invidam requested changes
빠르게 완성했네요! 👍

리뷰 확인해주세요~

2023-05-04 05:34 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    @RequestMapping(value = "/admin/owner/{ownerId}/permission/shops/{shopId}", method = RequestMethod.PUT)
`~/permission?shopId=123` vs `~/permission/shops/{shopId}` 중에 후자로 한 이유가 있을까요?

그리고 상점 매핑을 상점 명이 아닌 ID로 해도 괜찮나요?

2023-05-04 05:34 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        adminShopMapper.updateShopOwnerId(ownerId, shopId);
설명을 못했던 것 같은데,
grant_shop 도 0 -> 1로 변경해야 됩니다 😅

2023-05-04 06:07 UTC, daheeParkk commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    @RequestMapping(value = "/admin/owner/{ownerId}/permission/shops/{shopId}", method = RequestMethod.PUT)
shopId가 필수값이라서 url에 명시하는게 좋다고 생각했습니다.
상점 명보다 id를 받는게 통일성 면에서 좋을 것 같고, 프론트에서 shopId를 줄 수 있다고 합니다!

2023-05-04 06:10 UTC, daheeParkk commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        adminShopMapper.updateShopOwnerId(ownerId, shopId);
넵 추가하겠습니다!

2023-05-08 13:49 UTC, daheeParkk commented
local swagger에서 테스트 해봤을 때 mysql에서 

- `owners` 테이블의 `grant_shop`이 1로 변환
- `users` 테이블의 `is_authed`가 1로 변환
- `shops` 테이블에 `owner_id' 매핑

위 세 가지가 동작하는 것을 확인해봤습니다.

2023-05-09 00:28 UTC, Invidam commented
5/8이후 얘기된 대로, 
1. 사장님 인증 + 가게 매핑 API와
2. 사장님 인증 API
완성 부탁해요~  ψ(｀∇´)ψ

2023-05-09 02:26 UTC, daheeParkk commented
shop id를 필수가 아닌 걸로 바꾸려 했는데 api가 두 개 필요한가요?
@Invidam

2023-05-09 14:29 UTC, Invidam commented
> shop id를 필수가 아닌 걸로 바꾸려 했는데 api가 두 개 필요한가요?

shop id를 필수가 아닌 걸로만 바꿈 되겠네요~

2023-05-15 07:38 UTC, daheeParkk commented
변경 사항 : shopId를 nullable로 변경

로컬에서 진행한 테스트입니다.
- ownerId만 넣었을 경우
  - is_authed와  grant_shop이 바뀌는지 확인
- ownerId와 shopId를 넣었을 경우
  -  is_authed와  grant_shop이 바뀌는지 확인
  - shops 테이블에 owner_id가 바뀌는지 화인

2023-05-15 09:28 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        }
메서드로 빼도 좋을 것 같아요

2023-05-15 09:44 UTC, Invidam approved these changes
**is_deleted가 true인 상점에 대해서도 매핑이 되는데 이렇게 처리되도 괜찮을까요?**

2023-05-15 09:44 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +                                                       @ApiParam(value = "shopId") @RequestParam(value = "shopId", required = false) Integer shopId) throws Exception {
`required = false` 👍

2023-05-15 09:44 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        }
메서드로 빼도 좋을 것 같아요!

2023-05-15 09:44 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +import io.swagger.models.auth.In;
?

2023-05-15 12:44 UTC, daheeParkk commented
변경 사항 : is_deleted 된 상점의 id와 사장님의 id가 매핑되지 않도록 수정

로컬에서 진행한 테스트입니다.
- shop의 is_deleted를 1로 바꾼 경우
  - 404 에러를 반환하는지 확인
- shop의 is_deleted를 0으로 바꾼 경우
  -  is_authed와  grant_shop이 바뀌는지 확인
  - shops 테이블에 owner_id가 바뀌는지 화인

2023-05-15 13:44 UTC, merged