Feature: 어드민 특정 학생 수정 api
BCSDLab/KOIN_API pull request #222
Opened 2023-05-02 14:19 UTC by tmdgus1715

### 주요 변경 사항
* 기존의 AdminUserController의 updateUser메서드 삭제 및 updateStudent메서드 추가
* 기존의 AdminUserService의 updateUserForAdmin메서드 삭제 및 updateStudentForAdmin메서드 추가
* 새로운 열거형 예외 추가 (GENDER_INVALID)

### 해결해야 할 주요 문제
* 커스텀한 422예외의 별도 처리시 에러 코드가 전부 100000으로 출력 됨.

2023-05-02 14:41 UTC, johnny19991006 commented on pom.xml
> +        </dependency>-->
pom.xml올리면 안될거 같아요!!!

2023-05-02 14:41 UTC, johnny19991006 commented on pom.xml
> +        </dependency>-->
sql버젼

2023-05-03 07:21 UTC, Invidam requested changes
메서드 분리해서 깔끔하게 예외처리가 됐네요~ 👍

수정할 사항들이 좀 있어, 리뷰 참고해 수정 부탁드릴게요!

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +        adminUserService.updateStudentForAdmin(request, id);
request가 service에 들어가기 전 xss check가 이루어져야 합니다!

[xss check](https://docs.google.com/document/d/1Cv_XmYbLzYw7k03-A0FhXP6vkXixMTZ-WCoc3lTeh_Y/edit)
참고해보세요!

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/user/student/request/StudentUpdateRequest.java
> +    }
빌더 패턴을 이용한 건 괜찮네요!

하지만 DTO <-> Domain 매핑은 mapstruct 이용해서 하구 있어요
UserConvertor의 toStudent 참고해고해서 수정해야할 것 같아요!

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/exception/ExceptionInformation.java
> -    NOT_OWNER("회원의 신원이 사장님이 아닙니다.", 101018, HttpStatus.CONFLICT),
NOT_OWNER이 삭제되면 안돼요!

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserService.java
> +    void updateStudentForAdmin(StudentUpdateRequest updateUserRequest, int id);
메서드명에서 `ForAdmin`은 없어도 될 것 같아요!
(`AdminUserService` 에서 Admin에서 이미 명시해주고 있어서)

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    ResponseEntity updateStudent(@ApiParam(value = "(optional: nickname, gender, major, student_number, phone_number)", required = false)
```
ResponseEntity<StudentResponse> updateUser(@RequestBody @Valid StudentUpdateRequest request, BindingResult bindingResult)
```
이 UserController쪽 학생 업데이트 부분인데, 참고해서 논의 해봐야 할 부분이 있어보여요

1. 응답시 StudentResponse라는 json 데이터(업데이트된 학생 정보)를 보내주지 않아도 되는지?
2. `PUT /admin/users/student/{id}` 을 사용해야 하는지? `PUT /admin/users/student` 으로 바꿀 순 없을지?

클라이언트 측과 논의해봐야할 것 같아요~

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +    }
메서드로 추출이 잘되었네요! 👍

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        student.setIs_graduated(selectUser.getIs_graduated());//is_graduated 수정 막음.
👍 필요한 기능입니다!

2023-05-03 07:21 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/user/student/request/StudentUpdateRequest.java
>  import javax.validation.constraints.Pattern;
`dto/normal` 이 아니라 `dto/admin` 에서 작업이 되야겠네요

-> dto/admin으로  dto/normal에서 작업했던 DTO들을 
1. StudentUpdateRequset, UserUpdateRequest 구조로 
2. admin-student-update에 적합한 형태로
옮겨야 되겠네요

왜냐면 admin과 normal이 수정할 수 있는 내용이 다를 수도 있어서

2023-05-10 11:09 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/user/student/request/StudentUpdateForAdminRequest.java
> +public class StudentUpdateForAdminRequest extends UserUpdateRequest {
`ForAdmin`은 컨벤션 상 없애기로 한 부분이라 떼면 좋을 것 같아요!
(admin 패키지에 속한다는 걸로 문맥을 파악할 수 있다고 결론내렸어요)

2023-05-13 06:54 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
>          studentMapper.updateStudent(selectUser);
작업중 궁금한 점이 있어서 질문드립니다!
이 부분에서 Mapper클래스를 admin이 아닌 normal을 사용해도 문제가 없나요?

2023-05-13 08:44 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
>          studentMapper.updateStudent(selectUser);
현재는 기능상 학생 업데이트 시에 admin과 normal의 수정 가능한 부분의 차이가 없기 때문에 문제가 없습니다.
하지만, admin과 normal의 DTO를 분리하여 추후에 수정 가능 부분의 차이가 생길 수 있으므로, Mapper도 admin과 normal을 구분하여 사용하는 것이 바람직하겠네요. 감사합니다!

2023-05-13 16:12 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
>          studentMapper.updateStudent(selectUser);
지금은 차이가 없더라도, 나중에  차이가 발생한다고 가정해야 합니다.
기한이 많이 넘긴 작업이라 추후 수정한다고 치고 넘어가야 할 듯하네요.

2023-05-13 16:13 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
xss가 먼저 적용되야 합니다

2023-05-13 16:23 UTC, Invidam commented
일욜까지 리뷰 남긴 사항들 반영(+ 코멘트로 반영했음을 명시)해주세요~
말 그대로 `Changes requested` 이고 무조건 변경할 필요가 있어요

2023-05-14 04:54 UTC, tmdgus1715 commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
적용했습니다

2023-05-14 04:55 UTC, tmdgus1715 commented on src/main/java/koreatech/in/dto/admin/user/student/request/StudentUpdateForAdminRequest.java
> +public class StudentUpdateForAdminRequest extends UserUpdateRequest {
적용했습니다.

2023-05-14 04:55 UTC, tmdgus1715 commented on src/main/java/koreatech/in/dto/normal/user/student/request/StudentUpdateRequest.java
>  import javax.validation.constraints.Pattern;
적용했습니다

2023-05-14 04:56 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/admin/AdminUserService.java
> +    void updateStudentForAdmin(StudentUpdateRequest updateUserRequest, int id);
적용했습니다

2023-05-14 04:56 UTC, tmdgus1715 commented on src/main/java/koreatech/in/exception/ExceptionInformation.java
> -    NOT_OWNER("회원의 신원이 사장님이 아닙니다.", 101018, HttpStatus.CONFLICT),
수정했습니다!

2023-05-14 04:56 UTC, tmdgus1715 commented on src/main/java/koreatech/in/dto/normal/user/student/request/StudentUpdateRequest.java
> +    }
수정했습니다

2023-05-14 04:56 UTC, tmdgus1715 commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +        adminUserService.updateStudentForAdmin(request, id);
적용했습니다

2023-05-14 05:43 UTC, tmdgus1715 commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    ResponseEntity updateStudent(@ApiParam(value = "(optional: nickname, gender, major, student_number, phone_number)", required = false)
기한이 많이 지난 작업이라 일단 이전처럼 업데이트된 학생 정보 반환하도록 적용했습니다. 반환 데이터는 admin과 normal로 구분하였습니다.

2023-05-14 06:00 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/user/response/UserUpdateResponse.java
> +}
end of line

2023-05-14 06:02 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        if (selectUser == null) {
다음부턴, 라인 포맷 적용할 때 본인이 작업하지 않은 내용에 영향을 안가도록 해주세요~

2023-05-14 06:21 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    ResponseEntity updateStudent(@ApiParam(value = "(optional: nickname, gender, major, student_number, phone_number)", required = false)
`ResponseEntity<StudentUpdateResponse>` 로 명시해주세요

2023-05-14 06:22 UTC, Invidam commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    ResponseEntity updateStudent(@ApiParam(value = "(optional: nickname, gender, major, student_number, phone_number)", required = false)
호환성 생각하면 기존 API가 있긴 해야겠네요 
일단 기존걸로 갑시다

2023-05-14 06:25 UTC, Invidam commented on pom.xml
> +        </dependency>-->
pom.xml은 절대로 변경되면 안됩니다.
깃헙-젠킨스가 없었고, 프로덕션-스테이지 구분이 안되어있었다면
코인 서버가 터졌을거에요

2023-05-14 06:58 UTC, tmdgus1715 commented on src/main/java/koreatech/in/controller/admin/AdminUserController.java
> +    ResponseEntity updateStudent(@ApiParam(value = "(optional: nickname, gender, major, student_number, phone_number)", required = false)
적용했습니다

2023-05-14 06:58 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        if (selectUser == null) {
알겠습니다!

2023-05-14 06:58 UTC, tmdgus1715 commented on src/main/java/koreatech/in/dto/admin/user/response/UserUpdateResponse.java
> +}
적용했습니다

2023-05-15 05:28 UTC, tmdgus1715 commented on pom.xml
> +        </dependency>-->
적용했습니다

2023-05-16 05:36 UTC, merged

2023-05-16 05:38 UTC, Invidam commented
## Feature: 어드민 특정 학생 수정 API
머지완료.

길고길었던 첫 작업 수고했어 👍
별 다른 오류없이 잘 동작하는 것 같네~

`#코인_프로젝트` 에 어떤 API 추가돼었는지 알려주면 될 듯!