Refactor: 메뉴 리스트 조회 응답 스키마 변경
BCSDLab/KOIN_API pull request #231
Opened 2023-05-15 14:35 UTC by songsunkook

## ▶ Request
### Content

#209 
### as-is
메뉴 리스트 조회 시 응답 스키마의 구조: 각 menu가 category_id를 리스트로 보유
```java
{
  "menus": [
    {
      (메뉴 정보),
      "category_ids": [
        (카테고리 id)
      ]
    }
}
```

### to-be
메뉴 리스트 조회 시 응답 스키마의 구조: 각 category별로 포함되는 menu 정보를 보유
기존 구조에서 추가적으로 카테고리명을 함께 반환
```java
{
  "categories": [
    {
      "id": (카테고리 id),
      "name": "카테고리명",
      "menus": [
        {
          (메뉴 정보)
        }
  ]
]
```

### 세부 구현 내용
- AllMenusOfShopResponse DTO 구조 변경
    - 사용처
        - /shops/{id}/menus
        - /owner/shops/{id}/menus

- 조회를 시도한 상점의 총 메뉴 개수를 반환 (기존 form 유지를 위해 제공)
    - response되는 메뉴의 총 개수는 아님
        - 단일 메뉴가 복수의 메뉴 카테고리 보유 시 여러 카테고리에서 반환됨

## ✅ Check List
- [x] 의도치 않은 변경이 일어나지 않았는지.
  - 실수로 라이브러리(`pom.xml`) 변경이 일어나지 않았는지
  - 병합시 컴파일 & 런타임 에러가 발생하지 않는지
  - 기존 클라이언트와의 호환성 고려가 잘 이루어졌는지
- [x] 작성한 코드가 프로젝트에 반영됨을 명심하였는지
  - 타인도 알아보고 변경할 수 있는 코드를 작성하였는지
  - 코드 & 커밋 컨벤션을 준수하였는지
  - (필요한) 문서화가 진행되었는지
- [x] (기능 추가의 경우) 클라이언트의 입장에 대한 충분한 고려가 이루어졌는지
  - 클라이언트 측과 협의가 된 내용인 경우
  - 클라이언트의 요구사항을 잘 반영하는지
  - API 문서에 논리적인 오류 & 가시성이 떨어지는 내용이 없는지

## 📸 API Document ScreenShot
![image](https://github.com/BCSDLab/KOIN_API/assets/21010656/e15a1370-5d66-4275-9392-ec9ac5dac0f4)
![image](https://github.com/BCSDLab/KOIN_API/assets/21010656/99b6143d-694b-417d-a600-79c18b425048)

## 🧪 Test

- [x] 총 메뉴 개수(count)가 정상적으로 반환되는지 확인
- [x] 각 카테고리의 id와 함께 name이 정상적으로 반환되는지 확인
- [x] 단일 메뉴가 복수의 메뉴 카테고리 보유 시 정상적으로 반환되는지 확인
- [x] 점주용 상점 메뉴 조회 API 호출 시 자신의 상점이 아니라면 403 error(권한 없음)가 발생하는지 확인
    - 일반 상점용 상점 메뉴 조회 API 호출 시 자신의 상점 유무와 관계없이 동작 확인

2023-05-15 14:38 UTC, ChoiWonBeen commented
admin은...?

2023-05-15 14:41 UTC, songsunkook commented
@ChoiWonBeen 
헉... 지금 작업하러 가겠습니다... 죄송합니다!!

2023-05-15 15:48 UTC, songsunkook commented
변경 사항 : admin 특정 상점 모든 메뉴 조회 API에도 해당 구조 개선 적용

테스트 사항
- GET /admin/shops/{id}/menus API 호출 시 정상적으로 개선된 구조가 반환되는지 확인

2023-05-16 02:09 UTC, Invidam requested changes
응답은 잘 이루어지네요~

리뷰 남긴 한 가지 사항만 꼭 반영해주세요!

2023-05-16 02:09 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/shop/response/AllMenusOfShopResponse.java
>                  .build();
다음부턴 mapstruct에서 dto <-> domain 간 변환을 수행하면 좋겠어요

2023-05-16 02:09 UTC, Invidam commented on src/main/java/koreatech/in/repository/ShopMapper.java
> -}
👍

2023-05-16 02:09 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerShopServiceImpl.java
> +        return AllMenusOfShopResponse.from(menuProfiles, categoryNames);
팩터리 메서드에서,
인자가 1개일 떈 `from`을 쓰지만
2개 이상일 땐 `of`를 사용합니다.

2023-05-16 02:09 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/shop/response/AllMenusOfShopResponse.java
> +                .collect(Collectors.toList());
👍

2023-05-16 02:09 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/shop/response/AllMenusOfShopResponse.java
> +                                            .collect(Collectors.toList()).get(0).getName()
`get(0)` 이 존재한다는 근거가 빈약합니다. 
DB상에 NOT_NULL이라고 해서 무조건 존재한다고 가정하는 건 위험할 것 같습니다. 

-> 리스트로 만들고 0번째 원소를 가져올 거면 다음과 같이 구성해야 할 것 같습니다.
```suggestion
categoryNames.stream()
.filter(categoryName -> categoryName.getId().equals(categoryIndex))
.findFirst()
.orElse({예외 처리 로직})
.getName()
```

- 일반적으로는 DB 상에서 join을 이용해 shopId와 함께 shopName을 가져오는 방식을 취할것 같습니다. (게시판 서비스에서 댓글 사용자의 ID와 이름 모두 가져오는 것처럼)

2023-05-18 15:23 UTC, Invidam commented on src/main/java/koreatech/in/dto/admin/shop/response/AllMenusOfShopResponse.java
> +                                            .collect(Collectors.toList()).get(0).getName()
요기도 바껴야 할 듯합니다!!

2023-05-18 16:45 UTC, songsunkook commented on src/main/java/koreatech/in/dto/admin/shop/response/AllMenusOfShopResponse.java
>                  .build();
넵 다음부터는 참고하겠습니다!

2023-05-18 16:45 UTC, songsunkook commented on src/main/java/koreatech/in/service/OwnerShopServiceImpl.java
> +        return AllMenusOfShopResponse.from(menuProfiles, categoryNames);
넵 수정하겠습니다!

2023-05-18 16:45 UTC, songsunkook commented on src/main/java/koreatech/in/dto/normal/shop/response/AllMenusOfShopResponse.java
> +                                            .collect(Collectors.toList()).get(0).getName()
확실한 근거가 없는 가정은 위험할 수 있다!
기억해두겠습니다..!!

2023-05-18 16:45 UTC, songsunkook commented on src/main/java/koreatech/in/dto/admin/shop/response/AllMenusOfShopResponse.java
> +                                            .collect(Collectors.toList()).get(0).getName()
죄송합니다. 수정완료했습니다!!

2023-05-19 02:07 UTC, merged