Feature/admin update owner api2
BCSDLab/KOIN_API pull request #235
Opened 2023-05-25 06:18 UTC by johnny19991006

## ▶ Request
### Content
이슈번호 234
### as-is

### to-be

## ✅ Check List
- [ ] 의도치 않은 변경이 일어나지 않았는지.
  - 실수로 라이브러리(`pom.xml`) 변경이 일어나지 않았는지
  - 병합시 컴파일 & 런타임 에러가 발생하지 않는지
  - 기존 클라이언트와의 호환성 고려가 잘 이루어졌는지
- [ ] 작성한 코드가 프로젝트에 반영됨을 명심하였는지
  - 타인도 알아보고 변경할 수 있는 코드를 작성하였는지
  - 코드 & 커밋 컨벤션을 준수하였는지
  - (필요한) 문서화가 진행되었는지
- [ ] (기능 추가의 경우) 클라이언트의 입장에 대한 충분한 고려가 이루어졌는지
  - 클라이언트 측과 협의가 된 내용인 경우
  - 클라이언트의 요구사항을 잘 반영하는지
  - API 문서에 논리적인 오류 & 가시성이 떨어지는 내용이 없는지

## 📸 API Document ScreenShot

![image](https://github.com/BCSDLab/KOIN_API/assets/79901434/f288968c-7d06-4960-a25a-e42bd7ae20ed)

## 🧪 Test

- [ x] 어드민 학생 수정검증시 본인제외후 검증 해결
- [ x] 수정이 필요할때만 업데이트하게 바

2023-05-27 06:17 UTC, Invidam requested changes
오류가 있어 리뷰 확인해서 수정이 필요할 것 같아요 ㅠ

그래도 옵셔녈 활용, 메서드 분리 등 좋은 코드를 위해 노력한 게 보이네요! 

추가적으로,
1. PR 제목, 브랜치 명을 명확하게 표현해야 할 것 같아요 (admin-owner-update에 대한 코드들은 아닌 듯)
2. API Screenshot에는 
![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/5b66ae9c-7197-49dd-8815-46d322acd450)
처럼 빨간 표시된 부분이 들어가면 보기 좋을 것 같아요
3. 테스트를 상세하게 표현하여 오류 점검, 가독성 향상이 되면 좋겠어요
  - 테스트에 필요한 내용
    - 테스트에 넣은 값 (다른 사람도 테스트해볼 수 있도록)
    - 원하는 테스트 결과
    - 실제 테스트 결과
  - 테스트 범위
    - 정상 동작 테스트
    - 예외 처리 테스트
  - 등등

2023-05-27 06:17 UTC, Invidam commented on src/main/resources/mapper/normal/UserMapper.xml
> +        SELECT COUNT(*)
일반적으로 `isXXX()` 메서드는 XXX인지 여부 (True/ Flase) [Boolean]을 반환하는 것이 컨벤션입니다! 

따라서 Boolean을 반환하도록 수정하면 좋을 것 같아요

2023-05-27 06:17 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +    private void isDuplicateNickname(Student student, Integer userId) {
## isXXX
일반적으로 isXXX() 메서드는 XXX인지 여부 (True/ Flase) [Boolean]을 반환하는 것이 컨벤션입니다!

따라서 검증만 수행할 거면 메서드 명이
```suggestion
    private void validateDupication()
```
이어야 할 것 같아요

## 인자 전달
사소하지만, `Student student` 내부에 `id`가 있을 것 같은데, 굳이 id값을 인자로 전달할 필요가 없을 것 같아요 ㅎ

2023-05-27 06:17 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +        }
👍

2023-05-27 06:17 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +
본인이 작업한 내용 이외의 내용들까지 변경되지 않도록 주의합시다!

2023-05-27 06:17 UTC, Invidam commented on src/main/resources/mapper/normal/UserMapper.xml
> +            LIMIT 1;
`AND is_deleted = 0` 가 있을 때,
이미 삭제한 사용자가  해당 닉네임을 사용하고 있는 경우가 고려가 안되서 **500 에러**가 뜨네요 

수정 바랍니당 ( #206 의 몇몇 쿼리문들도 문제가 있네요)

2023-05-28 05:33 UTC, johnny19991006 commented on src/main/resources/mapper/normal/UserMapper.xml
> +        SELECT COUNT(*)
넵! 메서드 이름을 바꾸어 보겠습니다

2023-05-28 05:34 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +    private void isDuplicateNickname(Student student, Integer userId) {
넵 저부분도 다시 해결하겠습니다!!

2023-05-28 05:34 UTC, johnny19991006 commented on src/main/resources/mapper/normal/UserMapper.xml
> +            LIMIT 1;
넵!

2023-05-28 14:45 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +    private void isDuplicateNickname(Student student, Integer userId) {
지금 계속된 오류로 디버깅을 통해 살펴보니, student(혹은 owner)로 표시된 dto에서 userId는 받지 않아서 따로 userId파라미터를 가져와야 할것 같습니다.(저번 작업을 할때 그렇게 생각을 했었는데, 다시보니 잊은것 같습니다.)

2023-05-28 15:50 UTC, johnny19991006 commented on src/main/resources/mapper/normal/UserMapper.xml
> +            LIMIT 1;
궁금한 점이 혹시 normal student test시 500error가 발생한건가요?
제가 처음에 메서드를 만들었을때,  id인자가 전달이 안되어 오류가 발생한것 같은데,(위의 인자 관련 댓글) 만약 그러한 에러라면 AND is deleted는 오류가 없어보여 질문드립니다.(일단 제거하고 올리긴 하였으나 기능상 이상이 없어보여 그렇습니다.)

2023-05-28 16:06 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +
넵 주의하겠습니다

2023-05-29 02:42 UTC, Invidam commented on src/main/resources/mapper/normal/UserMapper.xml
> +            LIMIT 1;
제 설명이 부실했네요~
예시를 들자면
1. 현재 쿼리문은 is_deleted 가 0 인 사용자들 중에서**만** 닉네임 중복을 찾음.
2. User `{"id": 123, "nickname": "Invidam", "is_deleted": "true" }` 가 DB에 들어가 있다면, 닉네임 중복 체크시 고려되지 않음.
3. User `{"id": 4885, "nickname": "Invidam"}` 인 유저를 추가한다면 닉네임 중복체크시 사용 가능한 닉네임이라고 뜸.
4. 위 사용자를 DB에 넣게된다면, DB에서 같은 닉네임이 있기 때문에 중복에러가 뜨고, catch가 안되서 그대로 500 에러를 응답

이런 경우가 발생합니다!


정리해보면
현재 상황: 중복검사가 모든 범위를 고려하지 않고, is_deleted가 0인 경우만 고려함
문제 배경: 새로운 사용자의 데이터와 is_deleted = 1 인 사용자의 데이터가 중복이 되는 경우
문제 결과: 중복체크에서 중복을 잡지 못하고 삽입됨 ->  DB에서 unique 제약조건 위배 ->  예외 발생 -> 500에러가 뜸

2023-05-30 01:07 UTC, Invidam commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +    private void isDuplicateNickname(Student student, Integer userId) {
세터로 넣어주면 되지 않을까요?

2023-05-30 01:10 UTC, Invidam commented on src/main/java/koreatech/in/service/UserServiceImpl.java
> +                throw new ConflictException(new ErrorMessage("nickname duplicate", 1));
중복되는 검증을 잘 찾아냈네요!

BaseException을 던져주면 컨벤션에 더 적합할 것 같아요

2023-05-30 01:25 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/UserServiceImpl.java
> +                throw new ConflictException(new ErrorMessage("nickname duplicate", 1));
위에 주석으로 위 기능은 안쓴다고 남겨져 있어 따로 수정 안했습니다!

2023-05-30 01:39 UTC, johnny19991006 commented on src/main/resources/mapper/normal/UserMapper.xml
> +            LIMIT 1;
자세한 설명 감사합니다.
그러면 삭제가 된 닉네임까지 검증할수 있게 isdeleted는 없어져야 겠네요~

2023-05-30 01:41 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/UserServiceImpl.java
> +                throw new ConflictException(new ErrorMessage("nickname duplicate", 1));
![image](https://github.com/BCSDLab/KOIN_API/assets/79901434/0d74edf6-7775-45d3-a25a-99cc50493ff4)

2023-05-30 02:43 UTC, johnny19991006 commented on src/main/java/koreatech/in/service/admin/AdminUserServiceImpl.java
> +    private void isDuplicateNickname(Student student, Integer userId) {
제가 mapstruct에 대한 이해가 부족해서 그랬던것 샅습니다.
한번 수정해 볼게요~

2023-05-31 00:01 UTC, Invidam commented on src/main/resources/mapper/normal/UserMapper.xml
> +            LIMIT 1;
해당 부분은 Admin-Owner Update도 같은 증상일 것 같은데 수정 계획이 어떻게 될까요?

2023-05-31 00:23 UTC, johnny19991006 commented on src/main/resources/mapper/normal/UserMapper.xml
> +            LIMIT 1;
admin owner update도 같은 mapper파일을 사용중이라 같이 수정됩니다!

2023-05-31 05:49 UTC, Invidam commented
잘 동작하네요! 
머지했습니다.

젠킨스 빌드한 후 프로젝트 채널에 안내해주면 될 것 같아요!

2023-05-31 05:50 UTC, merged