Refactor/owner register api
BCSDLab/KOIN_API pull request #238
Opened 2023-05-26 16:57 UTC by tmdgus1715

## ▶ Request
### Content
#223 
### as-is
회원가입 과정에서, 사장님이 상점에 관한 정보를 입력하지 않아, 어떤 상점의 사장님인지 알 수 없었음.
### to-be
- [x] `StringRedisUtilStr` 대신 `StringRedisUtilObj `를 이용하도록 변경
  - as-is: `Gson`을 이용하여 String <-> Json간 변환하여 저장 & 조회하였음.
  - 변경 사항: `StringRedisUtilObj`를 활용하여 key-value 형식으로 Json을 저장 & 조회함.
- [x] 전화번호, 상점 명, 상점 ID를 입력
  ![image](https://github.com/BCSDLab/KOIN_API/assets/71889359/e3cee45f-7e09-4a39-9235-9ec72f0ad53c)
  - 사장님이 입력한 개인 전화번호는 Database에 저장
  - 사장님이 요청한 상점 명,상점 ID는 Redis에 owner_shop@(prefix) + {ownerId} 의 key형식으로 저장
- [x] 사업자등록번호 & 파일 첨부를 옵셔널로 변경
  - service에서 검증
  - **아무것도 입력 안하거나** 혹은 **모두 입력하거나** 둘 중 하나에 만족해야 함.
- [ ] Admin 사장님 수정 & 조회 변경 (**전화번호 및 요청한 상점 ID, 상점 명** 수정 & 조회)
- [ ] Normal 사장님 수정 & 조회 변경 (**전화번호** 수정 조회)
- [ ] (추후) 사업자 등록번호 검증
  - https://imspear.tistory.com/m/114

## ✅ Check List
- [x] 의도치 않은 변경이 일어나지 않았는지.
  - 실수로 라이브러리(`pom.xml`) 변경이 일어나지 않았는지
  - 병합시 컴파일 & 런타임 에러가 발생하지 않는지
  - 기존 클라이언트와의 호환성 고려가 잘 이루어졌는지
- [x] 작성한 코드가 프로젝트에 반영됨을 명심하였는지
  - 타인도 알아보고 변경할 수 있는 코드를 작성하였는지
  - 코드 & 커밋 컨벤션을 준수하였는지
- [ ] (필요한) 문서화가 진행되었는지
  - **에러 관련, 문서화 진행 예정**
- [x] (기능 추가의 경우) 클라이언트의 입장에 대한 충분한 고려가 이루어졌는지
  - 클라이언트 측과 협의가 된 내용인 경우
  - 클라이언트의 요구사항을 잘 반영하는지
  - API 문서에 논리적인 오류 & 가시성이 떨어지는 내용이 없는지

## 📸 API Document ScreenShot

## 🧪 Test

- [x] 기존 코드의 정상 동작 확인 
- [x] 전화 번호 db에 저장 확인
- [x] redis에 사장님 가게 임시 요청 데이터 저장 확인
- [x] 회원 가입시 사업자 등록 정보(사업자 등록 번호, 첨부 파일) 불충분 시 422 에러 확인
- [x] 회원 가입시 사업자 등록 정보 둘 다 미포함 시에도 db에 첨부파일 제외하고 정상 저장 확인

2023-05-27 07:20 UTC, Invidam approved these changes
redis, flyway를 활용한 난이도 있는 기능임에도 잘 구현이 되었네요!

몇가지 수정 제안 있어 확인해주세요~

추가로, PR Template에서 체크리스트는 100% 체크가 될 수 있도록 해주세요 (모든 내용을 충족하거나, **필요없는 체크사항은 아예 삭제하거나**)

2023-05-27 07:20 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +    }
```suggestion
    public oolean isSufficientRegisterRequest(OwnerRegisterRequest request) {
        return !(hasCompanyNumber(request) ^ hasAttachmentUrls(request));
    }
```
처럼 긍정형으로 변경 + static 제거는 어떨까요?

2023-05-27 07:20 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/User.java
> +    @JsonIgnore
JsonIgore을 붙인 이유가 있을까요?

2023-05-27 07:20 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +    }
Owner 도메인 영역에서
OwnerRegisterRequest  DTO 영역을 참고하는 건 좋지 않아보여요!

2023-05-27 07:20 UTC, Invidam commented on src/main/java/koreatech/in/mapstruct/OwnerConverter.java
> +        return toOwner(ownerRegisterRequest);
toRestrictedOwner, toOwner 모두 동일한 Owner을 반환하는 것 보단
Owner을 상속한 다른 객체를 반환하는 건 어떨까요?

e.g. OwnerPartition (Owner의 일부 정보만을 가짐), OwnerDetails(Owner 정보 + 다른 정보를 가짐)

2023-05-27 07:20 UTC, Invidam commented on src/main/resources/db/migration/V72__alter_owners_company_registration_number_is_nullable.sql
V72_000__alter ~~.sql 로 작성하는 게 컨벤션에 맞을 것 같아요!
(`flyway_history`에 이미 들어가서 지금 변경은 어려워 보이네요 ㅋㅋㅋ;)

+) 컨벤션 문서에서 이해하기 어려웠던 부분이 있었다면 수정, 제안 주세요~

2023-05-27 07:20 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/user/owner/request/OwnerRegisterRequest.java
>              + "- 이미지는 최소 3개 최대 5개까지 허용됨 \n"
사업자등록번호와 첨부파일에 대해 아무것도 입력 안하거나 혹은 모두 입력하거나 둘 중 하나에 만족해야 함.
라는 내용을 swagger에서 명시해주어야 할 것 같아요!

2023-05-27 07:21 UTC, Invidam commented
@daheeParkk @tmdgus1715 
- [ ] Admin 사장님 수정 & 조회 변경 (전화번호 및 요청한 상점 ID, 상점 명 수정 & 조회)
- [ ] Normal 사장님 수정 & 조회 변경 (전화번호 수정 조회)
은 어떻게 처리할 계획인가요?

2023-05-27 08:13 UTC, tmdgus1715 commented
+ 사장님 권한 허용 시, redis에서 사장님 요청 데이터 제거
세 가지 사항 얘기 나눠보고 작업 분배 하겠습니다!

2023-05-28 10:53 UTC, tmdgus1715 commented on src/main/java/koreatech/in/domain/User/User.java
> +    @JsonIgnore
해당 프로퍼티는 Redis에 저장되지 않아도 되는 값입니다. 그렇기 때문에 @JsonIgnore로 직렬화할 때 제외하였습니다.

2023-05-28 12:09 UTC, tmdgus1715 commented on src/main/java/koreatech/in/dto/normal/user/owner/request/OwnerRegisterRequest.java
>              + "- 이미지는 최소 3개 최대 5개까지 허용됨 \n"
적용했습니다!

2023-05-28 12:10 UTC, tmdgus1715 commented on src/main/resources/db/migration/V72__alter_owners_company_registration_number_is_nullable.sql
컨벤션 지킬게요!

2023-05-28 12:10 UTC, tmdgus1715 commented on src/main/java/koreatech/in/mapstruct/OwnerConverter.java
> +        return toOwner(ownerRegisterRequest);
OwnerPartition으로 서브 클래스 만들어서 사용했습니다!

2023-05-28 12:18 UTC, tmdgus1715 commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +    }
DTO와 도메인의 결합도를 줄여야하는 것에는 동의합니다!
하지만 궁금한 것은, 그러면 도메인 객체가 아닌 dto에 메시지를 보내 응답을 받아야 하나요?
-  dto는 단순히 계층간 데이터 전송을 위한 클래스이므로 getter, setter외의 비즈니스 로직은 들어가면 안된다고 알고있는데 그러면, 서비스에서 getter로 정보를 얻어와서 registration_information을 가지고 있는지 확인해야 하나요?
-  현재 리팩토링한 방식은 dto에 hasXXX의 메소드를 정의했는데, dto에 정의한 이유는, 단순히 값이 있는지 확인만 하는 메소드가 비즈니스 로직인지 잘 모르겠어서 입니다.

2023-05-28 12:19 UTC, tmdgus1715 commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +    }
적용했습니다

2023-05-29 02:53 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/Owner.java
> +    }
우선 비지니스 로직이 들어가면 안되는거지, 검증 로직이 들어가면 안되는 건 아니라고 생각해요

다만 검증 로직의 경우는 상황, 컨벤션에 따라 Controller에서 검증할 수도 있고 Service에서 검증할 수도 있을 것 같아요

예를 들어서, 이메일 요청에 대해
- 컨트롤러: 이메일 형식인지 확인 (유효성 검증)
- 서비스: 이메일이 @koraetech.ac.kr 인지 확인 (비지니스와 연관된 검증)

이런식으로도 처리할 수 있을 것 같아요

2023-05-30 00:48 UTC, Invidam reviewed
리뷰 남겼어요! 
DTO 관련, Partition 관련해서 어떻게 처리할지 고민해보면 좋을 것 같아요

2023-05-30 00:48 UTC, Invidam commented on src/main/java/koreatech/in/mapstruct/OwnerConverter.java
> +            return toOwnerPartition(ownerRegisterRequest);
👍

2023-05-30 00:48 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        Owner owner = ownerConverter.toNewOwner(ownerRegisterRequest);
`ownerRegisterRequest` DTO는 서비스단의 로직이 실행되기 전에 도메인 객체로 변환해서 최대한 의존관계를 줄이면 좋을 것 같아요

검증 로직도 DTO 객체로 진행하는거면 차라리 컨트롤러 단에서 수행할 수도 있을 것 같고..

2023-05-30 00:48 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        OwnerConverter ownerConverter = OwnerConverter.INSTANCE;
컨버터 인스턴스를 `OwnerConverter ownerConverter` 로 선언한 이유가 있을까요?

2023-05-30 01:00 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/OwnerPartition.java
> +public class OwnerPartition extends Owner {
Owner을 상속하면서, Owner의 일부분만 가질 수 있을까요...??

2023-05-30 02:59 UTC, tmdgus1715 commented on src/main/java/koreatech/in/domain/User/owner/OwnerPartition.java
> +public class OwnerPartition extends Owner {
Owner를 상속하고 있지만 Owner의 일부분만 참조할 수 있도록 getter와 setter를 필요한 것만 오버라이딩 했습니다.

2023-05-31 00:00 UTC, Invidam commented on src/main/java/koreatech/in/domain/User/owner/OwnerPartition.java
> +public class OwnerPartition extends Owner {
오버라이딩 한다고해서, 일부분만 참조할 수 있는 건 아닌 것 같아요!
오버라이딩 하지 않은 게터 세터도 public이라 참조가 가능해서..

2023-06-06 06:38 UTC, tmdgus1715 reviewed
__주요 피드백 반영 사항__
-  커스텀 검증 어노테이션 사용
    - Dto내부의 검증 메소드 제거
    -  컨트롤러에서 @Valid로 검증 가능
- OwnerPartition은 접근 불가능 필드의 setter만 막은 채로, 다형성 활용 위해 현상 유지

2023-06-06 06:38 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        OwnerConverter ownerConverter = OwnerConverter.INSTANCE;
converter를 사용하는 부분이 해당 메소드내 여러 번 존재해서, 조금이라도 코드를 줄여보고자 선언했습니다

2023-06-06 06:38 UTC, tmdgus1715 commented on src/main/java/koreatech/in/domain/User/owner/OwnerPartition.java
> +public class OwnerPartition extends Owner {
다형성 활용위해서 일단 현상 유지하기로했고, Partition클래스에서 접근 불가능한 필드의 setter만 사용을 막았습니다.

2023-06-06 06:38 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        Owner owner = ownerConverter.toNewOwner(ownerRegisterRequest);
컨트롤러에서 @Valid로 검증할 수 있도록, 어노테이션 정의해서 dto의 검증 책임 제거했습니다.

2023-06-06 13:56 UTC, Invidam requested changes
shop_name 관련 선택으로 변경이 필요해보여요!

추가적으로 새로 도입된 validator을 모르는 팀원들을 위해 관련 설명을 블로깅 or 문서화 해도 좋을 것 같아요!

2023-06-06 13:56 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/user/owner/request/OwnerRegisterRequest.java
> +            ,required = true)
상점 선택 필수가 아니라 선택이어야 해요!

1. 상점이 코인에 이미 있는 사장님
2. 상점이 코인에 없지만 사장님

으로도 나뉘어서

2023-06-06 13:56 UTC, Invidam commented on src/main/java/koreatech/in/validator/OwnerValidator.java
> +            return !(companyNumberName == null ^ attachmentUrlsName == null);
해당 부분에 대해 잘 이해가 어려울 수도 있으니  메서드로 추출하는 것도 좋아보여요!

2023-06-14 04:54 UTC, tmdgus1715 commented on src/main/java/koreatech/in/dto/normal/user/owner/request/OwnerRegisterRequest.java
> +            ,required = true)
등록 시 , 상점 관련 정보 선택적 사항으로 변경 했습니다. (테스트까지 완료)

2023-06-14 04:55 UTC, tmdgus1715 commented on src/main/java/koreatech/in/validator/OwnerValidator.java
> +            return !(companyNumberName == null ^ attachmentUrlsName == null);
적용했습니다

2023-06-14 04:57 UTC, tmdgus1715 commented on src/main/java/koreatech/in/validator/OwnerValidator.java
> +            return !(companyNumberName == null ^ attachmentUrlsName == null);
검증 관련 커스텀 어노테이션 문서화해서 드라이브에 올리겠습니다!

2023-06-15 09:01 UTC, merged