Task: 비밀번호 변경을 위한 이메일 인증 번호 요청 기능
BCSDLab/KOIN_API pull request #270
Opened 2023-07-20 06:36 UTC by daheeParkk

## ▶ Request
### Content
#264 
### as-is

### to-be
**비밀번호 변경을 위해 이메일로 인증 번호 요청하는 API**
- [기존 이메일 변경 요청 api](https://github.com/BCSDLab/KOIN_API/pull/138)에서 key를 `owner_password_change@{email}`로 변경
- 폼에 이메일, 날짜(연도,월,일,시,분) 전달
<img width="767" alt="image" src="https://github.com/BCSDLab/KOIN_API/assets/106418303/c18fdc14-7f53-429d-9e27-88209d8052fd">

- 기존의 사장님이 맞는지 이메일 확인
  - 기존의 사장님 이메일이 아닐 경우 409 conflict 오류 발생

## ✅ Check List
- [x] 의도치 않은 변경이 일어나지 않았는지.
  - 실수로 라이브러리(`pom.xml`) 변경이 일어나지 않았는지
  - 병합시 컴파일 & 런타임 에러가 발생하지 않는지
  - 기존 클라이언트와의 호환성 고려가 잘 이루어졌는지
- [x] 작성한 코드가 프로젝트에 반영됨을 명심하였는지
  - 타인도 알아보고 변경할 수 있는 코드를 작성하였는지
  - 코드 & 커밋 컨벤션을 준수하였는지
  - (필요한) 문서화가 진행되었는지
- [x] (기능 추가의 경우) 클라이언트의 입장에 대한 충분한 고려가 이루어졌는지
  - 클라이언트 측과 협의가 된 내용인 경우
  - 클라이언트의 요구사항을 잘 반영하는지
  - API 문서에 논리적인 오류 & 가시성이 떨어지는 내용이 없는지

## 📸 API Document ScreenShot
<img width="652" alt="image" src="https://github.com/BCSDLab/KOIN_API/assets/106418303/e0286335-ad93-4cdd-a9ba-fbface80894d">

## 🧪 Test

- [x] 이메일로 폼이 전송되는지 확인
- [x] 기존의 사장님 신원의 이메일이 아닐 경우 409 오류가 발생하는지 확인
- [x] 유효하지 않은 이메일일 경우 오류가 발생하는지 확인

2023-07-20 12:46 UTC, Invidam approved these changes
이메일 관련 로직은 외부 서비스를 많이 활용하여 이해하기 어려웠을텐데 잘 구현이 되었네요 수고하셨어요 👍

**보면서 고민되는 건 이번 PR로 인해서 사장님-이메일 기능이 1개에서 여러 개로 추가되었는데, 이와 같이 여러 개의 이메일 기능이 생기게 된다면 어떻게 코드 중복을 줄일지가 고민되네요**

`requestVerification`, `requestVerificationToChangePassword`, `requestVerificationAAA` 같은 메서드가 계속 생겨나거나

`OWNER_CERTIFICATE_FORM_LOCATION` , `OWNER_PASSWORD_CHANGE_CERTIFICATE_FORM_LOCATION`, 
`OWNER_CERTIFICATE_FORM_XXX` 
같은 상수들이 수없이 많아진다면 어떻게 대처하는 게 좋을지 고민해보고 적용까지되면 좋을 것 같아요

2023-07-20 12:46 UTC, Invidam commented on src/main/java/koreatech/in/controller/OwnerController.java
> +                    code = 409,
409 응답은 이전 요청과 충돌(Conflict)일 경우 보낸다고 이해하고 있어 사장님 신원의 이메일이 아닌 경우와는 다른 상태라고 느껴지네요

사장님 목록중에서 이메일을 못찾았다는 의미에서 404를 반환해줄 수도 있을 것 같고
최대한 정보를 숨기기 위해(사장님 신원의 이메일이 아니라는 건 학생 신원의 누군가가 해당 이메일을 쓰고 있다고 알려주는 거겠죠?) 400 응답으로 얼버무릴 수도 있을 것 같아요

2023-07-20 12:46 UTC, Invidam commented on src/main/java/koreatech/in/controller/OwnerController.java
> +    @RequestMapping(value = "/owners/password/verification/email", method = RequestMethod.POST)
기존 API(`POST /user/find/password`)와 통일성있게 엔드포인트를 정하는 건 어떨까요?

2023-07-20 12:46 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +                    ownerInVerification, 2L, TimeUnit.HOURS);
2L 리터럴 대신 의미있는 상수로 표현하면 더 좋을 것 같아요 ㅋㅋㅋ

2023-07-20 12:46 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +    private String mailFormWithTimes(CertificationCode certificationCode, String emailAddress) {
```
// MailModel.java

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

public class MailModel {
    private Map<String, Object> model;

    private MailModel() {
        model = new HashMap<>();
    }

    public static MailModel builder() {
        return new MailModel();
    }

    public MailModel certificationCode(String certificationCode) {
        model.put(CERTIFICATION_CODE, certificationCode);
        return this;
    }

    public MailModel emailAddress(String emailAddress) {
        model.put(EMAIL_ADDRESS, emailAddress);
        return this;
    }

    public MailModel dateTime(LocalDateTime dateTime) {
        model.put(YEAR, dateTime.getYear());
        model.put(MONTH, dateTime.getMonthValue());
        model.put(DAY_OF_MONTH, dateTime.getDayOfMonth());
        model.put(HOUR, dateTime.getHour());
        model.put(MINUTE, dateTime.getMinute());
        return this;
    }

    public Map<String, Object> build() {
        return model;
    }
}

```

이런식으로 빌더패턴 이용해서 구성할 수도 있을 것 같고,
```
// MailService.java

public class MailService {
    // ...

    public String mailFormWithTimes(CertificationCode certificationCode, String emailAddress) {
        LocalDateTime now = LocalDateTime.now();
        Map<String, Object> model = MailModel.builder()
                .certificationCode(certificationCode.getValue())
                .emailAddress(emailAddress)
                .dateTime(now)
                .build();
    
        return VelocityEngineUtils.mergeTemplateIntoString(
                velocityEngine, 
                OWNER_PASSWORD_CHANGE_CERTIFICATE_FORM_LOCATION,
                StandardCharsets.UTF_8.name(), 
                model
        );
    }
}

```

이런식으로 이메일 관련 역할을 OwnerService 에서 별도 EmailService로 빼낼 수도 있을 것 같아요

지피티 이용해서 대략적으로 만든거라 이런 느낌이구나 정도만 이해해주세요 ㅎ

2023-07-20 12:46 UTC, Invidam commented on src/main/resources/mapper/normal/UserMapper.xml
> +    <select id="isOwnerEmail" parameterType="koreatech.in.domain.User.EmailAddress" resultType="Boolean">
새로운 메서드를 만드는 대신 기존에 있던 `getUserByEmail`을 이용해서 가져온 사용자가 1. 있는지 2. 사장님인지 를 검증하는 건 어떨까요?

가능하면 기존 API들을 활용하여 복잡성을 줄이는 게 이점이 있을 것 같아요

2023-07-21 04:02 UTC, knight7024 commented on src/main/java/koreatech/in/controller/OwnerController.java
> +                    code = 409,
알려준거 바로 써먹네

2023-07-25 15:18 UTC, Invidam requested changes
회원가입 요청 - 비밀번호 변경 요청 을 통일해서 처리할 수 있는 로직이 생긴 게 맘에 드네요 👍~
수고하셨습니다... ㅎㅎ

다만, 테스트코드가 없다보니 리팩터링 이후에 기존 로직이 잘 돌아가는 지에 대한 주의가 필요할 것 같아요!

2023-07-25 15:18 UTC, Invidam commented on src/main/java/koreatech/in/controller/OwnerController.java
> +    @RequestMapping(value = "/owner/find/password/verification", method = RequestMethod.POST)
1. 기존에는 기존 관례 지키자고 의견을 냈는데 **좋은 API을 디자인**하는 게 더 좋다고 알게됐습니다  (멘토님 덕에 😅) 따라서 저희만의 좋은 API를 디자인해보는 게 좋을 것 같아요!
2. 저도 고민해서 몇가지 생각해 놓은 것들 내일 공유해드릴테니 **내일까지 고민해보세요 ㅎㅎ**
3. Tips
- [디자인 참고 문서](https://covenant.tistory.com/241)
- 이번에 알게 되었는데, 카카오, 구글, Meta 등 다양한 API 문서들을 참고해 보는 것도 꿀팁인 것 같습니당

2023-07-25 15:18 UTC, Invidam commented on src/main/java/koreatech/in/dto/Mail.java
> +        return model;
저도 모르는 부분이 많아서 좋지않은 코드를 전달을 했던 것 같아요

제공했던 코드대로라면 
1. 일반적인 빌더 패턴과 부합하지 않아 이해하기 어려움
2. 필드가 불변을 만족하지 않음
같은 문제가 있을 것 같아

일반적인 빌더처럼 필드를 활용해서 빌드하고, 결과물인 객체를 Map으로 변환하는 편이 나을 것 같아요!

2023-07-25 15:18 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +                SesMailSender.OWNER_FIND_PASSWORD_EMAIL_VERIFICATION_SUBJECT);
`{ "mail/owner_certificate_number.vm", "코인 사장님 회원가입 이메일 인증"}`
`{"mail/change_password_certificate_number.vm", "코인 사장님 비밀번호 찾기 이메일 인증"}`

을 enum으로 관리하여 확장성, 가독성을 높이는 건 어떨까요!

2023-07-25 15:18 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        }
옵셔널 활용도 좋은 기술이지만 `if(user == null || user.isStudent()) -> throw ~~`  로 예외처리를 하는 게 보기 편할 것 같습니다!

2023-07-25 15:18 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        EmailAddress emailAddress = OwnerConverter.INSTANCE.toEmailAddress(verifyEmailRequest);
기존에는
1. `certificationCode`를 생성
2. `ownerInVerification`를 생성
3. `putRedisFor`, `sendMailFor` 에 생성한 객체들을 넣는다.
였는데

변경되었을 때는 
1. `certificationCode`를 2번 이상 생성
2. `ownerInVerification`를 2번 이상 생성
하게 되는 것 같아요!

이유가 있을까요..?

예상되는 사안들은
(2)는 불필요한 걸 줄이면 성능 향상, 가독성이 좋아질 수 있을 것 같고
(1)은 이메일로 보낸 인증번호와 저장소에 저장된 인증번호가 달라질 것 같아 논리적인 오류가 발생할 것 같아요 ㅠ..

2023-07-25 15:31 UTC, daheeParkk commented on src/main/java/koreatech/in/controller/OwnerController.java
> +    @RequestMapping(value = "/owner/find/password/verification", method = RequestMethod.POST)
넵 고민해보겠습니당..!

2023-07-27 09:01 UTC, daheeParkk commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        EmailAddress emailAddress = OwnerConverter.INSTANCE.toEmailAddress(verifyEmailRequest);
기존 코드의 순서 (redis에 넣고 이메일 전송)를 지키면서 코드 중복을 줄여보려고 이렇게 변경했습니당...
인증번호를 따로 생성하면 달라진다는 것을 생각 못 했습니다 ㅠㅠ
이메일 전송하고 반환한 인증번호를 redis에 넣으면 될 것 같습니다!

2023-07-27 09:02 UTC, daheeParkk commented on src/main/java/koreatech/in/controller/OwnerController.java
> +    @RequestMapping(value = "/owner/find/password/verification", method = RequestMethod.POST)
`/owners/password/reset/email` 은 어떤가요..?!

2023-07-27 11:31 UTC, Invidam commented on src/main/java/koreatech/in/controller/OwnerController.java
> +    @RequestMapping(value = "/owner/find/password/verification", method = RequestMethod.POST)
오 비슷하네요~

저는
```

/owners/registeration/email/verification
/owners/registeration/email/code


/owners/password-reset/email/verification
/owners/password-reset/email/code
```

저는
1. reset을 굳이 계층으로 분리하지 않아도 될 것 같고,
2. 앞으로 추가될 이메일-인증번호 검증 같은 API를 고려하면 email 뒤에 또 다른 표현(`verification`)이 필요하다 생각했어요

2023-07-27 13:48 UTC, daheeParkk commented on src/main/java/koreatech/in/controller/OwnerController.java
> +    @RequestMapping(value = "/owner/find/password/verification", method = RequestMethod.POST)
reset을 계층으로 분리하지 않은 게 회원가입과 통일성 있어보여서 더 괜찮은 것 같아요!
```
/owners/registeration
/owners/registeration/email/verification
/owners/registeration/email/code

/owners/password-reset
/owners/password-reset/email/verification
/owners/password-reset/email/code
```
이렇게 진행하도록 하겠습니다!

2023-08-02 12:06 UTC, Invidam commented on src/main/java/koreatech/in/controller/OwnerController.java
> +    @RequestMapping(value = "/owner/find/password/verification", method = RequestMethod.POST)
회원가입은 철자가 registration 이네요 😅

1. 이메일을 통해서 통신한다는 건 body에 나와있으니 경로에선 없애도 될 것 같고,
2. `/passsword-reset`대신 `/passsword/reset `으로 표현하여 `/password/ABC` 등의 URL의 확장성 고려도 할 수 있을 것 같아요

```
POST /api/password/reset/verification
{
  code: "1234"
}

POST /api/password/reset/send
{
  email: "abc@def.com"
}
```

2023-08-20 11:23 UTC, daheeParkk commented
다음과 같은 부분을 개선하였습니다!

- 비밀번호 변경 api, 회원가입 api URL 변경
    - 비밀번호 변경
        - /owners/password/reset
    - 비밀번호 변경 인증번호 전송 (예정)
        - /owners/password/reset/send
    - 비밀번호 변경 인증번호 입력 (예정)
        - /owners/password/reset/verification      
    - 회원가입
        - /owners/registration
    - 회원가입 인증번호 전송
        - /owners/registration/send
    - 회원가입 인증번호 입력
        - /owners/registration/verification
        
- Mail build하고 Map으로 변환
- enum 클래스로 mail form 경로, 제목 관리
- 메일이 없는 경우 예외처리 방식 변경
- `certificationCode` 과 `ownerInverification` 한 번씩만 생성

로컬에서 한 테스트입니다.

- 인증 번호가 메일로 오는지 확인
- 메일이 학생이 아니거나 없는 메일일 경우 예외가 발생하는지 확인
- 이메일로 온 인증 번호가 redis의 인증 번호와 같은지 확인
- 코드 변경 후에도 회원 가입 인증 번호 api가 돌아가는지 확인

2023-08-26 13:42 UTC, Invidam reviewed
리뷰했던 사항들이 잘 반영된 것 같아요! 👍👍

몇가지 의견 남겼으니 참고해주세요!

2023-08-26 13:42 UTC, Invidam commented on src/main/java/koreatech/in/service/MailService.java
> +        Map<String, Object> model = mail.convertToMapWithTimes(mail);
`mail.convertToMapWithTimes(mail)` 에서 인자에 mail은 필요가 없을 것 같아요!

2023-08-26 13:42 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/mail/MailForm.java
확장성이 있어 좋은 것 같아요! 👍 
MailForm은 dto 패키지안에 있는데, dto로 분류하는 게 맞을까요?

저는 메일 전송이 Service에서 처리하는 비지니스 로직이라고 생각해서, 
메일 전송과 관련된 enum은 계층간 변환(Transform)이 일어나진 않는 것 같다고 생각합니다!

2023-08-26 13:42 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        CertificationCode certificationCode = mailService.sendMail(emailAddress, OWNER_REGISTRATION_MAIL_FORM.getPath(),
MailForm객체 자체를 넘겨줄 수도 있을 것 같아요!

2023-08-27 14:06 UTC, daheeParkk commented on src/main/java/koreatech/in/service/MailService.java
> +        Map<String, Object> model = mail.convertToMapWithTimes(mail);
제대로 확인을 못했습니다..ㅠㅠ 수정하겠습니다!

2023-08-27 14:07 UTC, daheeParkk commented on src/main/java/koreatech/in/dto/normal/mail/MailForm.java
MailForm은 DB와 관련이 없다는 생각에 DTO로 넣었습니당.. 아직 Domain과 DTO에 대한 공부가 부족한 것 같습니다😢

2023-08-27 14:08 UTC, daheeParkk commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        CertificationCode certificationCode = mailService.sendMail(emailAddress, OWNER_REGISTRATION_MAIL_FORM.getPath(),
MailForm 객체를 넘겨주면 sendMail()의 안에서만 긴 코드가 있고, sendMail()을 사용하는 여러 곳에서는 코드의 길이가 줄어들 수 있을 것 같네요..! 수정하겠습니당!

2023-08-27 14:10 UTC, daheeParkk commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        CertificationCode certificationCode = mailService.sendMail(emailAddress, OWNER_REGISTRATION_MAIL_FORM.getPath(),
다른 이유가 있다면 알려주실 수 있나요!

2023-08-27 14:38 UTC, daheeParkk commented
다음과 같은 부분을 개선하였습니다.
- mail.convertToMapWithTimes(mail) 에서 인자에 mail 제거
- MailForm 클래스를 domail 패키지 안으로 이동
- 메일 전송 메서드에 MailForm 객체를 전달하도록 변경


로컬에서 한 테스트입니다.
- 이메일 입력 시 제목, 날짜, 시간, 인증번호가 맞게 전송되는지 확인
- 회원가입 인증번호 요청 api에 이메일 입력 시 제목, 인증번호가 맞게 전송되는지 확인

2023-09-03 14:33 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        CertificationCode certificationCode = mailService.sendMail(emailAddress, OWNER_REGISTRATION_MAIL_FORM.getPath(),
가독성도 좋아질 것 같고 객체의 메서드를 이용하여 여러 활용이 가능해서 확장성도 있을 것 같아요

2023-09-18 01:46 UTC, merged