Feature/ownershop request slack notice
BCSDLab/KOIN_API pull request #288
Opened 2023-09-23 06:52 UTC by tmdgus1715

## ▶ Request
### Content

### as-is
#285  
### to-be
사장님이 회원가입 시 본인의 상점 연결을 위해 상점 정보를 보내면 이를 관리자가 직접 연결해주기 위해 슬랙후커를 통해 알림을 보낸다.

## ✅ Check List
- [x] 의도치 않은 변경이 일어나지 않았는지.
  - 실수로 라이브러리(`pom.xml`) 변경이 일어나지 않았는지
  - 병합시 컴파일 & 런타임 에러가 발생하지 않는지
  - 기존 클라이언트와의 호환성 고려가 잘 이루어졌는지
- [x] 작성한 코드가 프로젝트에 반영됨을 명심하였는지
  - 타인도 알아보고 변경할 수 있는 코드를 작성하였는지
  - 코드 & 커밋 컨벤션을 준수하였는지
  - (필요한) 문서화가 진행되었는지
- [x] (기능 추가의 경우) 클라이언트의 입장에 대한 충분한 고려가 이루어졌는지
  - 클라이언트 측과 협의가 된 내용인 경우
  - 클라이언트의 요구사항을 잘 반영하는지
  - API 문서에 논리적인 오류 & 가시성이 떨어지는 내용이 없는지

## 📸 API Document ScreenShot

## 🧪 Test

- [x] `로컬에서 테스트 완료 `
<img width="551" alt="image" src="https://github.com/BCSDLab/KOIN_API/assets/115052407/fa71c866-8825-435f-9843-f1dbc3a48ac8">

2023-09-24 11:11 UTC, Invidam reviewed
수고했어요~ 👍

슬랙 알림 부분 조사하며 알게된 게 있으면 문서 정리해도 좋을 것 같아요

2023-09-24 11:11 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        }
ownerShop이 null인 경우가 없다면 
`noticeOnwerShopRequest(owner, ownerShop);` 을 사용하지 않고 `slackNotiSender.noticeOwnerShopRequest(owner);` 을 사용하는 게 역할 분리 관점에서 더 나아보여요! 

추가로 널체크가 필요하다고 해도,  `ownerShop`의 데이터 자체가 활용되진 않으니 인자로 들어오는 게 어색하게 느껴지기도 합니당

2023-09-24 11:11 UTC, Invidam commented on src/main/java/koreatech/in/domain/NotiSlack.java
> +    public static final String OWNERSHOP_REQUEST_SUFFIX = "님이 상점연결을 요청하셨습니다.";
private이 될 수 있을 것 같아요!

2023-09-25 02:09 UTC, johnny19991006 reviewed
이미 앞에서 리뷰를 자세히 남겨주셔서 별로 남길게 없네요.
고생많으셨어요~!!

2023-09-25 02:09 UTC, johnny19991006 commented on src/main/java/koreatech/in/domain/NotiSlack.java
> +                .build();
Class명을 만드실때 Notice, Noti를 나누신 이유가 있을까요?
Builder패턴 Good!!

2023-09-25 02:09 UTC, johnny19991006 commented on src/main/java/koreatech/in/domain/NotiSlack.java
> +    public static final String OWNERSHOP_REQUEST_SUFFIX = "님이 상점연결을 요청하셨습니다.";
그러면 위에 있는 다른 인자까지 private이 되는 것이 맞을까요?

2023-10-12 06:31 UTC, tmdgus1715 commented on src/main/java/koreatech/in/domain/NotiSlack.java
> +    public static final String OWNERSHOP_REQUEST_SUFFIX = "님이 상점연결을 요청하셨습니다.";
수정했습니다

2023-10-12 06:33 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +        }
이전 사장님회원가입 로직 분리가 되기전 코드라서 ownershop을 받을 수밖에 없었습니다
일단은 코멘트 주신것처럼 수정했으며, 사장님 로직 분리가 머지가 되면 상점정보를 추가한 사장님 회원가입 로직에 한하여 해당 로직(`slackNotiSender.noticeOwnerShopRequest(owner)`를 추가하겠습니다!

2023-10-12 13:32 UTC, Invidam requested changes

2023-10-12 13:32 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> -
`slackNotiSender.noticeOwnerShopRequest(owner);` 의 호출 자체가 사라진 것 같아요~

2023-10-13 03:59 UTC, johnny19991006 approved these changes

2023-11-21 07:44 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> -
앞서서 머지할게 있어서 일부러 비워놨습니다!

2023-11-21 07:44 UTC, tmdgus1715 commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> -
앞서서 머지할게 있어서 일부러 비워놨습니다~

2023-12-17 14:02 UTC, merged