Task: 비밀번호 변경을 위한 비밀번호 입력 기능
BCSDLab/KOIN_API pull request #290
Opened 2023-09-25 08:28 UTC by daheeParkk

## ▶ Request
### Content
#264 
### as-is

### to-be
**비밀번호 변경을 위해 비밀번호를 입력하는 API**
- 이메일과 비밀번호를 같이 받는 OwnerFindPasswordRequest DTO 생성
- 사장님 이메일인지 확인
- 이메일로 redis 확인
    - redis에 있는가 (= 인증 시간 만료 되었는가)
    - 인증이 true인가
- 비밀번호 변경
    - 비밀번호 암호화
- redis에서 제거

## ✅ Check List
- [x] 의도치 않은 변경이 일어나지 않았는지.
  - 실수로 라이브러리(`pom.xml`) 변경이 일어나지 않았는지
  - 병합시 컴파일 & 런타임 에러가 발생하지 않는지
  - 기존 클라이언트와의 호환성 고려가 잘 이루어졌는지
- [x] 작성한 코드가 프로젝트에 반영됨을 명심하였는지
  - 타인도 알아보고 변경할 수 있는 코드를 작성하였는지
  - 코드 & 커밋 컨벤션을 준수하였는지
  - (필요한) 문서화가 진행되었는지
- [x] (기능 추가의 경우) 클라이언트의 입장에 대한 충분한 고려가 이루어졌는지
  - 클라이언트 측과 협의가 된 내용인 경우
  - 클라이언트의 요구사항을 잘 반영하는지
  - API 문서에 논리적인 오류 & 가시성이 떨어지는 내용이 없는지

## 📸 API Document ScreenShot
<img width="585" alt="image" src="https://github.com/BCSDLab/KOIN_API/assets/106418303/785aa3c3-c2e7-4403-b143-ef0946f0716b">

## 🧪 Test

- [x] 오류 테스트
    - 인증이 안된 이메일일 경우 오류 테스트
    - redis에 없는 이메일일 경우 오류 테스트
- [x] redis 테스트
    - 비밀번호가 변경될 때 redis의 정보가 삭제 되는지 확인
- [x] 코드가 변경된 회원가입 api도 잘 동작하는지 확인

2023-09-25 13:27 UTC, Invidam requested changes
리뷰 남겼어요!
비밀번호 찾기 기능이 개선 작업이 많아져 할 게 굉장히 많았을텐데, 잘해주셨네요 👍

진행하며 배우는 게 많았길 빕니당.. 😸

2023-09-25 13:27 UTC, Invidam commented on src/main/java/koreatech/in/repository/RedisOwnerMapper.java
> +    public void validateOwnerInRedis(EmailAddress emailAddress, RedisOwnerKeyPrefix redisOwnerKeyPrefix) {
**redis**OwnerMapper.validateOwnerIn**Redis**

라고 코드가 되면, redis라는 표현이 중복되는 것 같아 없어도 될 것 같아요!

2023-09-25 13:27 UTC, Invidam commented on src/main/java/koreatech/in/dto/normal/user/owner/request/OwnerFindPasswordRequest.java
> +public class OwnerFindPasswordRequest {
- API URL: reset password
- method name: change password
- object name: find password
라고 되어있어서 용어의 통일이 필요할 것 같아요!

API URL은 클라이언트에게 제공되야해서 용어가 다를 수 있을 것 같은데,
메서드, 객체는 통일하면 이해가 편리할 듯 합니당

2023-09-25 13:27 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +    private User validateEmailFromOwner(EmailAddress emailAddress) {
`Owner validAndGetOwnerFromEmail(Email email)`로 사용하면 (+ User 대신 Email 반환)
1. 검증
2. 이메일로 부터 사장님 객체 반환
두 가지 역할을 가지고 있다는 걸 알릴 수 있고, 사장님 객체로의 변환도 메서드에서 수행할 수 있을 것 같아요!

2023-09-25 13:27 UTC, Invidam commented on src/main/java/koreatech/in/service/OwnerServiceImpl.java
> +    }
```suggestion
    }
    
```
😸

2023-09-25 13:27 UTC, Invidam commented on src/main/java/koreatech/in/mapstruct/OwnerConverter.java
> +    }
`@Mappings` 대신 `default` 키워드로 직접 구현한 이유가 있을까요?

2023-09-30 12:49 UTC, daheeParkk commented on src/main/java/koreatech/in/mapstruct/OwnerConverter.java
> +    }
```java
@Mappings({
            @Mapping(source = "address", target = "localParts", qualifiedByName = "convertLocalParts"),
            @Mapping(source = "address", target = "domain", qualifiedByName = "convertDomain")
    })
    EmailAddress toEmailAddress(VerifyEmailRequest verifyEmailRequest);
```
기존 위의 메서드를 이용하여 OwnerFindPasswordRequest를 EmailAddress로 바꾸고 싶었는데, 
기존 메서드는 VerifyEmailRequest 타입을 인자로 받고 있어서 사용할 수 없었습니다.
그래서 다른 타입이 들어와도 위 메서드를 사용할 수 있도록 `EmailAddress toEmailAddress(String address);` 이렇게 바꾸고, 클래스 별로 .getAddress()하여  `toEmailAddress()`로 전달하는 메서드를 각각 만들었습니다.

2023-09-30 13:15 UTC, daheeParkk commented on src/main/java/koreatech/in/dto/normal/user/owner/request/OwnerFindPasswordRequest.java
> +public class OwnerFindPasswordRequest {
넵! 메서드는 비밀번호를 변경하는 기능을 하기 때문에 change password로 통일하겠습니다!

2023-09-30 13:38 UTC, daheeParkk commented
- 수정한 부분
    - 메서드 이름 변경
        - redisOwnerMapper.validateOwnerInRedis() **→** redisOwnerMapper.validateOwner() 로 이름 변경
        - redisOwnerMapper.getOwnerInRedis() → redisOwnerMapper.getOwner() 로 이름 변경
    - DTO 이름 변경
        - OwnerFindPasswordRequest() → OwnerChangePasswordRequest() 로 이름 변경
    - 메서드 끝난 후 한 줄 띄움

- 로컬 테스트
    - 비밀번호 전송 요청  api→ 인증번호 입력 api → 비밀번호 변경 api가 잘 동작하는지 확인
    - 비밀번호 변경 api가 동작 후 redis에서 owner 정보가 사라지는지 확인

2023-10-01 13:28 UTC, Invidam commented
잘 고쳐졌네요! 
커밋 단위를 지금처럼 잘 나눠준다면 별도 코멘트로 변경사항을 알려주지 않아도 될 것 같아요! (테스트 사항만 알려주면 될 것 같아요)

내일까지 다른 리뷰 없으면 머지할게요~ 수고했어요 👍

2023-10-02 15:50 UTC, merged