Feature: 학점 조회 기능 추가
BCSDLab/KOIN_API pull request #366
Opened 2024-03-26 02:20 UTC by kwoo28

## ▶ Request
### Content
#365 

### as-is

### to-be

## ✅ Check List
- [ ] 의도치 않은 변경이 일어나지 않았는지.
  - 실수로 라이브러리(`pom.xml`) 변경이 일어나지 않았는지
  - 병합시 컴파일 & 런타임 에러가 발생하지 않는지
  - 기존 클라이언트와의 호환성 고려가 잘 이루어졌는지
- [ ] 작성한 코드가 프로젝트에 반영됨을 명심하였는지
  - 타인도 알아보고 변경할 수 있는 코드를 작성하였는지
  - 코드 & 커밋 컨벤션을 준수하였는지
  - (필요한) 문서화가 진행되었는지
- [ ] (기능 추가의 경우) 클라이언트의 입장에 대한 충분한 고려가 이루어졌는지
  - 클라이언트 측과 협의가 된 내용인 경우
  - 클라이언트의 요구사항을 잘 반영하는지
  - API 문서에 논리적인 오류 & 가시성이 떨어지는 내용이 없는지

## 📸 API Document ScreenShot

## 🧪 Test
2개의 학기를 시간표 추가하고 해당학기학점, 전체학기학점를 확인했습니다.

2024-03-27 01:35 UTC, daheeParkk requested changes
수고하셨습니다!

2024-03-27 01:35 UTC, daheeParkk commented on src/main/java/koreatech/in/service/TimeTableServiceImpl.java
> +    private int calculateTotalGrades(int userId){
### A

```suggestion
    private int calculateTotalGrades(int userId) {
```
띄어쓰기 해주면 좋을 것 같아요!

2024-03-27 01:35 UTC, daheeParkk commented on src/main/java/koreatech/in/service/TimeTableServiceImpl.java
> +            put("전체학기학점", calculateTotalGrades(user.getId()));
### C
다른 api처럼 영어로 응답하는게 좋을 것 같아요!

2024-03-28 09:42 UTC, daheeParkk approved these changes
수고하셨습니다!

2024-03-28 09:59 UTC, duehee reviewed
고생하셨어요~ 코멘트 확인해주세요!

2024-03-28 09:59 UTC, duehee commented on src/main/java/koreatech/in/service/TimeTableServiceImpl.java
> +            put("grades", currentGrades);
C

grade보다는 credit을 사용하는 것은 어떨까요? crade는 학점보다는 성적 느낌이 조금 큰 것 같아요!

2024-03-28 09:59 UTC, duehee commented on src/main/java/koreatech/in/service/TimeTableServiceImpl.java
> +            put("total_grades", calculateTotalGrades(user.getId()));
C

위와 동일합니다

2024-03-28 10:01 UTC, duehee approved these changes
고생하셨어요~ 리뷰 확인해주세요!
-> ###을 사용했는데도 글씨가 안 커져요 ㅜㅜㅜ

2024-03-29 01:17 UTC, kwoo28 commented on src/main/java/koreatech/in/service/TimeTableServiceImpl.java
> +            put("grades", currentGrades);
감사합니다. 근데 DB에는 이수학점이 grade로 돼있는데.. 관습상 grade로 통일하는건 어떤가요..?

2024-03-29 03:35 UTC, duehee commented on src/main/java/koreatech/in/service/TimeTableServiceImpl.java
> +            put("grades", currentGrades);
앗..! 그렇다면 그냥 grade를 사용하는 게 좋아보이네요!

2024-03-31 06:18 UTC, merged